# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
 - linux
 - osx

julia:
 - 1.0

 after_success:
     # push coverage results to Coveralls
  - julia -e 'cd(normpath(Base.find_package("FixedPointAcceleration"), "..", "..")); using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

notifications:

email: false
