site_name:           FixedPointrepo_url:            https://github.com/s-baumann/FixedPointsite_description:    Description
site_author:         Stuart Baumann & Margaryta Klymak
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Tutorial:
  - Main Function: tutorials/Schumaker.md
  - Example Application: tutorials/Example.md
